DROP TABLE VERTEILER CASCADE CONSTRAINTS;
DROP TABLE STRANG CASCADE CONSTRAINTS;
DROP TABLE PFANNE CASCADE CONSTRAINTS;
DROP TABLE KOKILLE CASCADE CONSTRAINTS;
DROP TABLE EZV_GRUPPE CASCADE CONSTRAINTS;
DROP TABLE EZV CASCADE CONSTRAINTS;
DROP TABLE PARAMETER CASCADE CONSTRAINTS;
DROP TABLE PARAMETER_EZV CASCADE CONSTRAINTS;
DROP TABLE TEXT_PARAM CASCADE CONSTRAINTS;
DROP TABLE PATTERN_PARAM CASCADE CONSTRAINTS;
DROP TABLE CHARGE CASCADE CONSTRAINTS;
DROP TABLE TIME_TABLE CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_JUNCTION CASCADE CONSTRAINTS;
DROP TABLE PRODUKT CASCADE CONSTRAINTS;
DROP TABLE ChargenVerteiler CASCADE CONSTRAINTS;
DROP TABLE ChargenStrang CASCADE CONSTRAINTS;
DROP TABLE ChargenPfanne CASCADE CONSTRAINTS;
DROP TABLE ChargenKokille CASCADE CONSTRAINTS;
DROP TABLE ANLAGETEILNAME cascade constraints;
CREATE TABLE VERTEILER (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER,
    CONSTRAINT PK_Verteiler PRIMARY KEY (ID)
);

CREATE TABLE PFANNE (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER,
    CONSTRAINT PK_Pfanne PRIMARY KEY (ID)
);

CREATE TABLE KOKILLE (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER,
    CONSTRAINT PK_KOKILLE PRIMARY KEY (ID)
);

CREATE TABLE Strang (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER,
    CONSTRAINT PK_Strang PRIMARY KEY (ID)
);

CREATE TABLE EZV_GRUPPE(
    ID number,
    eID number,
    pID number,
    CONSTRAINT PK_EZVGruppe PRIMARY KEY (ID)
);

CREATE TABLE EZV(
    ID NUMBER,
    EZV_GRUPPE_ID NUMBER,
    NAME VARCHAR2(100),
    CONSTRAINT PK_EZV PRIMARY KEY (ID)
    );

CREATE TABLE PARAMETER(
    ID NUMBER,
    NAME VARCHAR2(100),
    ISTEXT NUMBER(1),
    ISCORDINATE NUMBER(1),
    ISPATTERN NUMBER (1),
    EINHEIT VARCHAR2(100),
    MESSZEITPUNKT timestamp,
    STANDARDWERT NUMBER,
    MAXIMUM NUMBER,
    MINIMUM NUMBER,
    CONSTRAINT PK_PARAMETER PRIMARY KEY (ID)
    );

CREATE TABLE PARAMETER_EZV(
    ID NUMBER,
    EZV_ID NUMBER,
    PARAMETER_ID NUMBER,
    MIN NUMBER,
    AIM NUMBER,
    MAX NUMBER,
    CONSTRAINT PK_PARAMETEREZV PRIMARY KEY (ID)
    );

CREATE TABLE PATTERN_PARAM(
    ID NUMBER,
    PATTERN_NO NUMBER,
    PATTERN_ID NUMBER,
    CONSTRAINT PK_PatternParam PRIMARY KEY (ID)
    );


CREATE TABLE TEXT_PARAM(
    ID NUMBER,
    PARAMETER_NO NUMBER,
    TEXT VARCHAR2(100),
    CONSTRAINT PK_TextParam PRIMARY KEY (ID)
);

CREATE TABLE Cordinate_Param(
    ID NUMBER,
    x number(16),
    y number(16),
    z number(16)
);

CREATE TABLE CHARGE( 
    id number,
    name varchar(32),
    EZV_ID number,
    weight number(10),
    positionID number,
    CONSTRAINT PK_Charge PRIMARY KEY (ID)
);

create Table Time_Table(
id number,
pfanneStart TIMESTAMP,
pfanneEnd TIMESTAMP,
VerteilerStart TIMESTAMP,
VerteilerEnd TIMESTAMP,
KokileStart TIMESTAMP,
KokileEnd TIMESTAMP,
strangStart TIMESTAMP,
strangENd TIMESTAMP,
CONSTRAINT PK_TimeTable PRIMARY KEY (ID)
);
--Product Junction

create Table PRODUCT_JUNCTION(
pID number,
cID number,
CONSTRAINT PK_ProductJunction PRIMARY KEY (pID,cID)
);

create table PRODUKT(
product_id number,
product_name varchar2(32),
charge_id number,
status number,
start_time TIMESTAMP,
end_time TIMESTAMP,
CONSTRAINT PK_Produkt PRIMARY KEY (product_id)
);

CREATE TABLE ChargenVerteiler (
    ID NUMBER,
    Verteiler_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenVerteiler PRIMARY KEY (ID)
);

CREATE TABLE ChargenStrang (
    ID NUMBER,
    Strang_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenStrang PRIMARY KEY (ID)
);

CREATE TABLE ChargenPfanne (
    ID NUMBER,
    Pfanne_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenPfanne PRIMARY KEY (ID)
);

CREATE TABLE ChargenKokille (
    ID NUMBER,
    Kokille_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenKokille PRIMARY KEY (ID)
);

CREATE TABLE ANLAGETEILNAME(
    ID NUMBER,
    name varchar(32)
);
INSERT INTO ANLAGETEILNAME values(1,'Pfanne');
INSERT INTO ANLAGETEILNAME values(2,'Verteiler');
INSERT INTO ANLAGETEILNAME values(3,'Kokille');
INSERT INTO ANLAGETEILNAME values(4,'Strang');