DROP TABLE FORMAT CASCADE CONSTRAINTS;
DROP TABLE VERTEILER CASCADE CONSTRAINTS;
DROP TABLE STRANG CASCADE CONSTRAINTS;
DROP TABLE PFANNE CASCADE CONSTRAINTS;
DROP TABLE KOKILLE CASCADE CONSTRAINTS;
DROP TABLE AREA CASCADE CONSTRAINTS;
DROP TABLE SUBAREA CASCADE CONSTRAINTS;
DROP TABLE EZV_GRUPPE CASCADE CONSTRAINTS;
DROP TABLE EZV CASCADE CONSTRAINTS;
DROP TABLE PARAMETER CASCADE CONSTRAINTS;
DROP TABLE PARAMETER_EZV CASCADE CONSTRAINTS;
DROP TABLE TEXT_PARAM CASCADE CONSTRAINTS;
DROP TABLE PATTERN_PARAM CASCADE CONSTRAINTS;
DROP TABLE CHARGE CASCADE CONSTRAINTS;
DROP TABLE TIME_JUNCTION CASCADE CONSTRAINTS;
DROP TABLE TIME_TABLE CASCADE CONSTRAINTS;
DROP TABLE PRODUCT_JUNCTION CASCADE CONSTRAINTS;
DROP TABLE PRODUKT CASCADE CONSTRAINTS;
DROP TABLE ChargenVerteiler CASCADE CONSTRAINTS;
DROP TABLE ChargenStrang CASCADE CONSTRAINTS;
DROP TABLE ChargenPfanne CASCADE CONSTRAINTS;
DROP TABLE ChargenKokille CASCADE CONSTRAINTS;
CREATE TABLE FORMAT(
    ID NUMBER,
    HOEHE NUMBER,
    BREITE NUMBER
);

CREATE TABLE VERTEILER (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER
);

CREATE TABLE PFANNE (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER
);

CREATE TABLE KOKILLE (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER
);

CREATE TABLE Strang (
    ID NUMBER,
    CurrentCharge number,
    AGE NUMBER
);


CREATE TABLE AREA(
    ID NUMBER,
    NAME VARCHAR2(100)
);

CREATE TABLE SUBAREA(
    ID NUMBER,
    AREA_ID NUMBER,
    NAME VARCHAR2(100)
);


CREATE TABLE EZV_GRUPPE(
    eID number,
    pID number
);

CREATE TABLE EZV(
    ID NUMBER,
    EZV_GRUPPE_ID NUMBER,
    NAME VARCHAR2(100)
    );

CREATE TABLE PARAMETER(
    ID NUMBER,
    NAME VARCHAR2(100),
    ISTEXT NUMBER(1),
    ISPATTERN NUMBER (1),
    EINHEIT VARCHAR2(100),
    MESSZEITPUNKT timestamp,
    STANDARDWERT NUMBER,
    MAXIMUM NUMBER,
    MINIMUM NUMBER
    );

CREATE TABLE PARAMETER_EZV(
    ID NUMBER,
    EZV_ID NUMBER,
    PARAMETER_ID NUMBER,
    MIN NUMBER,
    AIM NUMBER,
    MAX NUMBER
    );

CREATE TABLE PATTERN_PARAM(
    ID NUMBER,
    PATTERN_NO NUMBER,
    PATTERN_ID NUMBER
    );


CREATE TABLE TEXT_PARAM(
    ID NUMBER,
    PARAMETER_NO NUMBER,
    TEXT VARCHAR2(100)
);

CREATE TABLE CHARGE( 
    id number,
    EZV_ID number,
    weight number,
    positionID number
);

create Table Time_Table(
id number,
strangStart TIMESTAMP,
strangENd TIMESTAMP,
pfanneStart TIMESTAMP,
pfanneEnd TIMESTAMP,
VerteilerStart TIMESTAMP,
VerteilerEnd TIMESTAMP,
KokileStart TIMESTAMP,
KokileEnd TIMESTAMP
);



--Product Junction

create Table PRODUCT_JUNCTION(
pID number,
cID number
);

create table PRODUKT(
product_id number,
product_name varchar2(32),
charge_id number,
status number,
start_time TIMESTAMP,
end_time TIMESTAMP
);

CREATE TABLE ChargenVerteiler (
    ID NUMBER,
    Verteiler_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenVerteiler PRIMARY KEY (ID)
);

CREATE TABLE ChargenStrang (
    ID NUMBER,
    Strang_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenStrang PRIMARY KEY (ID)
);

CREATE TABLE ChargenPfanne (
    ID NUMBER,
    Pfanne_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenPfanne PRIMARY KEY (ID)
);

CREATE TABLE ChargenKokille (
    ID NUMBER,
    Kokille_ID Number,
    Chargen_ID Number,
    CONSTRAINT PK_ChargenKokille PRIMARY KEY (ID)
);